language: python
python:
- '2.7'
services:
- docker
before_install:
- chmod +x tests/*.sh
install:
- docker build -t sproxy-client/squid .
- docker run -di --name squid sproxy-client/squid
script:
- docker exec -it squid /tests/test_config.sh
- docker exec -it squid /tests/test_service.sh
notifications:
  email:
    recipients:
    - kevin.wang@microfusion.tw
    on_success: change
    on_failure: always
before_deploy:
- zip -r latest-${TRAVIS_BUILD_NUMBER}.zip *
- mkdir -p sproxy-client
- mv latest-${TRAVIS_BUILD_NUMBER}.zip sproxy-client/latest-${TRAVIS_BUILD_NUMBER}.zip
deploy:
   provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  repo: 60DMX/Aliyu-test.github.io
  target_branch: master

after_success:
  - git config --global user.name "kevin" 
  - git config --global user.email "kevin.wang@microfusion.tw"
  - sed -i'' "/^ *repo/s~github\.com~${GH_TOKEN}@github.com~" _config.yml
